jdbcSettings:
  url: "jdbc:mysql://127.0.0.1:3306/db_entity?useSSL=false&useInformationSchema=true"
  username: "root"
  password: "abcd1234"
  driverClassName: "com.mysql.jdbc.Driver"

packageName: "com.example.entity"

# for MS Windows : full path need
outputDirectory: "/workspace/GenerateJpaEntity/src/main/java"

classNameRules:
  - tableName: "posts"
    className: "Posts"
