jdbcSettings:
  url: "jdbc:mysql://127.0.0.1:3306/db_entity?useSSL=false&useInformationSchema=true"
  username: "root"
  password: "abcd1234"
  driverClassName: "com.mysql.jdbc.Driver"

packageName: "com.example.entity"

# ---------------------------------------------------------
# *** Rules for table/class name conversion ***

# If you need some rules that convert table names to entity class names, list the mapping rules as below.
#   - array of ClassNameRule objects
#     - tableName: table name (full name, case sensitive)
#     - className: Java class name to be used (you cannot include package namme in front of the class name)
classNameRules:
  - tableName: "posts"
    className: "Posts"
